### ISSUE TITLE
Found everything just have a question.

### ISSUE THREAD

**Issue by ghost** [hrt/BrawlBot#14]
Hey, your discoveries was a great stepping stone for me to get into reversing this game.

I have everything I need just I can't exactly tell the program which entity is mine.
I have not found anything that points back to my entity, or per say that I can tell the program, "Hey out of all these entities returned this one is mine!" 

Which brings me to my question? I see you have pointers. Which is weird because in my discovery Brawlhalla pointers are not stable. I have yet to find any actual pointer other than one that points to a VTable inside all the entities, "it's always located at the first address in all of them". How did you find a stable pointer?

**Comment by hrt** [comment]
To find base address of yourself you can see my comment over in offsets.py:
> # search for double 568.99 on demon map - it is your standing y
So I'd subtract y offset to get base from there.

I think with this I did have some troubles in finding a stable pointer to my own entity but eventually did manage with some tweaks that I can't remember.

To find all other entities I just did a memory scan for a certain pattern that entities have and kept track of them all. I knew which one was me based off the pointer from earlier.

**Comment by ghost** [comment]
Makes sense. I will keep looking. All I need to do is be able to distinguish between my entity and everyone else's, and I should be able to recreate what you've made, or per say more or less finish my bot. Anyways thanks for the reply!
