### ISSUE TITLE
Can't find PID

### ISSUE THREAD

**Issue by Zayoe4** [hrt/BrawlBot#3]
![image](https://user-images.githubusercontent.com/10657721/80781187-129d9200-8b37-11ea-88bf-1fe0d80c0202.png)
I am getting a "Can't find PID error" when attempting to run play.py.

I did some research and I found something similar:
https://github.com/n1nj4sec/memorpy/issues/10

On another note,
What do the variables `g_input_offsets` and `local_ptr_offsets` represent?
I'm guessing `g_input_offsets` have something to do with keyboard?
Also, does `local_ptr_offsets` mean local player offsets?

**Comment by Zayoe4** [comment]
Could you add me on discord:
zayoe4#6229
I also have questions about the champion list.

**Comment by Zayoe4** [comment]
When I searched I only managed to find the entity list of weapons. But I only knew what that list was after decompiling brawlhalla in jpex editor and studying the code. Did you use the same method?

**Comment by hrt** [comment]
> I am getting a "Can't find PID error" when attempting to run play.py.

Try running 64bit python2.



>I'm guessing g_input_offsets have something to do with keyboard?

`g_input_offsets` is for control input, if no buttons are pressed it holds 0 otherwise it is calculated like `calculate_actual_input` : https://github.com/hrt/BrawlBot/blob/master/play.py#L23



>Also, does local_ptr_offsets mean local player offsets?


`local_ptr_offsets` is just a pointer to your local legend


> How'd you know what each value is off of the entity list?

By just observing the memory region around the champion list and seeing what changes when I jump for example


>When I searched I only managed to find the entity list of weapons. But I only knew what that list was after decompiling brawlhalla in jpex editor and studying the code. Did you use the same method?


No, I just observed changing memory in cheat engine

**Comment by Zayoe4** [comment]
I'm currently using python version 2.7.18(tried both 64 and 32 bit). Should I be using an older version? 
I'm not fluent in python yet, so what dependencies should I have installed before I can run the program? So far, I've only installed memorpy and keyboard.

**Comment by hrt** [comment]
That error you see is not a dependency issue.

**Comment by Zayoe4** [comment]
I have brawlhalla installed on a different drive from python. I'll try to re-install python on the same drive and see if that changes anything.

**Comment by Zayoe4** [comment]
I'll keep troubleshooting and get back to you when I find a fix. 
Did you add me on discord. I had some friend request I hadn't accepted so I don't know who to accept. What's your discord name?

**Comment by hrt** [comment]
Not me

**Comment by Zayoe4** [comment]
No, I am asking you for your discord.

**Comment by hrt** [comment]
I like to use discord for just personal things.

**Comment by Zayoe4** [comment]
Understandable, I'm currently attempting to run on virtual enviornment to see if it is possibly a hardware issue.

**Comment by Zayoe4** [comment]
After leaving then coming back to this project, I finally realized that the reason that it can't get the PID is because I haven't updated offsets.py

On another note, after trying to deepen my understanding of memory, I seem to have hit a brick wall. Could you share a video of how you got those offsets? I think it'd really help me burst through and understand how to observe memory.

**Comment by jamunano** [comment]
@Zayoe4
https://youtu.be/EkrGp-he-yk

**Comment by jamunano** [comment]
@Zayoe4
https://youtu.be/EkrGp-he-yk

**Comment by Zayoe4** [comment]
Wait, what did the video show? I looks like he'd already found the offsets in that video. 
@jamunano

**Comment by hrt** [comment]
If you have nothing pressed it will hold 0.
If you are only pressing up then it holds 17 (at least it did for me).

Perhaps this is different for you. You could instead find it through changing values.

**Comment by Zayoe4** [comment]
I found both offsets, but it turns out, it was an issue with memorpy
The offsets I currently have are:
`offsets["local"] = (b'Adobe AIR.dll', [0x01315508,0x60,0x64,0x314,0x568,0x230,0x24])
offsets["ginput"] = (b'Adobe AIR.dll', [0x01315500,0x330,0x7C,0x4,0x2C,0xE4,0x4F4])`
I had to change `mem = MemWorker(name=PROCESS_NAME)` to `mem = MemWorker(pid = **_MANUALLY GET THE PID EACH LAUNCH_**)`
That fixed the issue for me. Documenting so others with same problem can see my duck taped solution.

**Comment by Zayoe4** [comment]
You can manually find the PID by opening task manager and going to the details tab.
Your pid should appear next to the process name. Look at the image below for reference:
![image](https://user-images.githubusercontent.com/10657721/91672233-daad5800-eaf2-11ea-8f7d-f651b33fffd8.png)

**Comment by fabiopsd** [comment]
@Zayoe4 @hrt 
 hi, i've never used python so i don't know how to show to all of you my problem. Could you add me on discord? Autovelox_is_real#7221

**Comment by Velocsy** [comment]
also i don't know how to install this: pip install https://github.com/hrt/memorpy/archive/master.zip
