### ISSUE TITLE
How can i update g_input_offsets and local_ptr_offsets?

### ISSUE THREAD

**Issue by lucasosilva** [hrt/BrawlBot#4]
I was adding new attacks, weapons, combos and strings to the bot however the last update of brawlhalla ended up breaking these addresses, how is it possible to get the new addresses?

g_input_offsets = ('Adobe AIR.dll', [0x0131550C, 0x1DC, 0x18, 0x8, 0x98, 0x1F8, 0x4CC])
local_ptr_offsets = ('Adobe AIR.dll', [0x01315528, 0xA4, 0x44C, 0x14, 0x98, 0x98, 0x548])

Is it possible to obtain them using the CE?

**Comment by hrt** [comment]
asked before: https://github.com/hrt/BrawlBot/issues/1
