### ISSUE TITLE
Error :(

### ISSUE THREAD

**Issue by Aghits** [hrt/BrawlBot#6]
Help please it shows this error

```
Traceback (most recent call last):
  File "play.py", line 341, in <module>
    main()
  File "play.py", line 11, in main
    local_ptr = dereference_offsets(mem, local_ptr_offsets)
  File "C:\Users\MSI\Desktop\BrawlBot-master\utils.py", line 38, in dereference_offsets
    ptr = mem.process.read(mem.Address(ptr + offset))
  File "C:\Python27\lib\memorpy\BaseProcess.py", line 53, in read
    return struct.unpack(s, self.read_bytes(int(address), bytes=l))[0]
struct.error: unpack requires a string argument of length 4
```

Do i need to update the g_input_offsets? if so how? i still didn't understand after reading this
`# ginput is just 0 ORed with whatever button you have pressed for example if you have up pressed then it'll be 17`

this is what i get https://prnt.sc/u7gss9 <- this is the y position but how do i get the other address

**Comment by Aghits** [comment]
New error 

`g_input: 0x6fa0fb4
local_ptr: 0x2d8d8ba0
Scanning memory for entities
Performing deep scan
Found 2 entities : 0x2c2f75c0L, 0x2c2f7ae0L
Removing local entity from entity list
Traceback (most recent call last):
  File "play.py", line 341, in <module>
    main()
  File "play.py", line 18, in main
    entity_pointers.remove(local_ptr)
ValueError: list.remove(x): x not in list`

**Comment by Aghits** [comment]
Ok now it works but no attack being perfomed...

need to update g_input_offsets i assume?

**Comment by Zayoe4** [comment]
Hey, sorry for the delayed response. The offsets I have for ginput are:
`offsets["ginput"] = (b'Adobe AIR.dll', [0x01315500,0x330,0x7C,0x4,0x2C,0xE4,0x4F4])`
Let me know if you need other offsets.

**Comment by Aghits** [comment]
> Hey, sorry for the delayed response. The offsets I have for ginput are:
> `offsets["ginput"] = (b'Adobe AIR.dll', [0x01315500,0x330,0x7C,0x4,0x2C,0xE4,0x4F4])`
> Let me know if you need other offsets.

local ptr offsets

**Comment by Aghits** [comment]
> Hey, sorry for the delayed response. The offsets I have for ginput are:
> `offsets["ginput"] = (b'Adobe AIR.dll', [0x01315500,0x330,0x7C,0x4,0x2C,0xE4,0x4F4])`
> Let me know if you need other offsets.

How did u get the offsets?

**Comment by Zayoe4** [comment]
I messaged you on discord.
