### ISSUE TITLE
Can ginput be used for target?

### ISSUE THREAD

**Issue by Zayoe4** [hrt/BrawlBot#7]
Can ginput be used to find the input for enemies? I've been trying to read the ginput of the enemy, but after days of testing, I've come up short. Were you able to find a way to get the enemy's current input(down light, neutral air, side signature, etc)

**Comment by hrt** [comment]
Not `ginput` that's purely input to your game.

If you observe the memory around the enemy pointer you could probably see what kind of attack they're performing - perhaps a specific number. But this might be a different value for a each character so you might have to create a list of your own attacks - for example, go through all the champions to create a list of "down light" attacks.

Above is just an educated guess from previous experience.

**Comment by Zayoe4** [comment]
I'll look into it, thanks!
